version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  playground:
    external: true

services:
  # nginx:
  #   networks:
  #     - playground
  #   image: nginx
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   restart: unless-stopped

  prometheus:
    networks:
      - playground
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=1y'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - '9090:9090'
    restart: unless-stopped

  cadvisor:
    networks:
      - playground
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - '8080:8080'
    deploy:
      mode: global
    restart: unless-stopped

  grafana:
    networks:
      - playground
    image: grafana/grafana
    user: '472'
    restart: always
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    env_file:
      - grafana/.env
    ports:
      - '3000:3000'

  playground:
    networks:
      - playground
    image: lodthe/clickhouse-playground:latest
    environment:
      CONFIG_PATH: /config.yml
    volumes:
      - ./config.yml:/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '9000:9000'
    restart: unless-stopped

  webapp:
    networks:
      - playground
    image: lodthe/clickhouse-playground-ui:latest
    restart: unless-stopped