version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  playground:
    external: true

services:
  # nginx:
  #   networks:
  #     - playground
  #   image: nginx
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   restart: unless-stopped
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: 2
  #         memory: 1g

  # nginx-prom-exporter:
  #   networks:
  #     - playground
  #   image: nginx/nginx-prometheus-exporter:0.10.0
  #   command: -nginx.scrape-uri="http://nginx:8080/stub_status"
  #   expose:
  #     - '9113'
  #   restart: unless-stopped
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: 0.5
  #         memory: 512m

  prometheus:
    networks:
      - playground
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=1y'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    expose:
      - '9090'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 6g

  cadvisor:
    networks:
      - playground
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
    expose:
      - '8080'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1g

  grafana:
    networks:
      - playground
    image: grafana/grafana
    user: '472'
    restart: always
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    env_file:
      - grafana/.env
    ports:
      - '3000:3000'
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2g

  playground:
    networks:
      - playground
    image: lodthe/clickhouse-playground:latest
    environment:
      CONFIG_PATH: /config.yml
    volumes:
      - ./config.yml:/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - '9000'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2g

  webapp:
    networks:
      - playground
    image: lodthe/clickhouse-playground-ui:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1g